In [11]:
import numpy as np 
print("Current numpy version being used::"+"["+np.__version__+"]")

Current numpy version being used::[1.20.3]


# 1. Numpy [Numerical Python]
## 1.1 (Arrays and Vectorized Computation)



In [6]:
import numpy as np

# how to create an array 
arr3 = np.arr

arr = np.array([1,2,3,4,5])
print(arr)




[1 2 3 4 5]


In [1]:
# creating array using arrange 

arr2 = np.arange(0,11)
print(arr2)

NameError: name 'np' is not defined

Numpy is used to work with arrays. The array object in numpy is called [ndarray].
narrays are created using the array|() function


In [13]:
print(type(arr2))
print(type(arr))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


## Dimension Arrays 
0-dim 
1-dim 
2-dim 


In [6]:
import numpy as np 
a = np.array(8)
#array with 0 dimensions 
print(a.ndim)

b = np.array([1,2,3])
print(b.ndim)

# 2d arrays 
c = np.array([[1,2,3],[4,5,6]])
print(c.ndim)
print(c)

d = np.array([1,2,3,4,5,6],ndmin=3)
print(d)




0
1
2
[[1 2 3]
 [4 5 6]]
[[[1 2 3 4 5 6]]]
