In [11]:
import numpy as np 
print("Current numpy version being used::"+"["+np.__version__+"]")

Current numpy version being used::[1.20.3]


# 1. Numpy [Numerical Python]
## 1.1 (Arrays and Vectorized Computation)



In [21]:
import numpy as np

# how to create an array 


arr = np.array([1,2,3,4,5])




In [18]:
# creating array using arrange 

arr2 = np.arange(0,11)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10]


Numpy is used to work with arrays. The array object in numpy is called [ndarray].
narrays are created using the array|() function


In [13]:
print(type(arr2))
print(type(arr))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


## Dimension Arrays 
0-dim 
1-dim 
2-dim 


In [6]:
import numpy as np 
a = np.array(8)
#array with 0 dimensions 
print(a.ndim)

b = np.array([1,2,3])
print(b.ndim)

# 2d arrays 
c = np.array([[1,2,3],[4,5,6]])
print(c.ndim)
print(c)

d = np.array([1,2,3,4,5,6],ndmin=3)
print(d)




0
1
2
[[1 2 3]
 [4 5 6]]
[[[1 2 3 4 5 6]]]


In [25]:
import numpy as np

q=np.array([[0,1,2],[3,4,5]])
print(q.ndim)
p=np.array([1,2,3],ndmin=2)
p.ndim
p.shape

"""_summary_
An ndarray is a generic multidimensional container for homogeneous data 
All the elements must be of the same datatype 
ndarray -- is the object
"""
p.dtype# data type 


2


dtype('int64')

In [35]:
"""
other ways fof creating arrays 
zeros 
arange
"""
z = np.zeros(10,dtype=int)
# provide the datatype eg int 

z.dtype

r = np.arange(10)
r
k = np.arange(2,10,2)
k

array([2, 4, 6, 8])

##### Dtypes  for ndarrays
used to specify the datatype of elements in the arrays 
The data type or dtype is a special object containing the information the ndarray needs
to interpret a chunk of memory as a particular type of data:

1. float 
2. int 


In [43]:
import numpy as np 
arr =  np.array([1,2,3], dtype=np.int0)
arr.dtype
arr1 =  np.array([1,2,3], dtype=np.float64)
arr.dtype


dtype('int64')

### operations with scalars 

express operations without writing any for loops 
This is cxalled vectorization 


In [52]:
a = np.array([1,2,3],dtype="int0")
b = np.array([4,5,6],dtype="int0")

a*b
a*2
b+2


array([6, 7, 8])

#### indexing and slicing 

In [78]:
arr = np.arange(10)
arr[0:5]
arr[3:5]
arr[1:5]=0
arr

# a=[1,2,3]
# a[1:2]=0

arr2d = np.array(([1,2,3],[4,5,6]))
arr2d[0][0:2]
arr2d[1][:]
arr2d[1][0:2]
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d.shape


(2, 2, 3)